spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:playerdb
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  config:
    use-legacy-processing: true
  h2:
    console:
      enabled: true

server:
  port: 8181
  include-debug-info: true
  error:
    include-message: always


# JWT Configuration
security:
  jwt:
    secret: DRQeqrJbHTooQiTSaBK9E0l22KwOQF/2pFEVo38ilHQ= # Replace with a strong secret key
    expiration-ms: 3600000  # 1 hour in milliseconds

# create secret key using openssl rand -base64 32
# fci@MacBook-Air backend-java-player-service % openssl rand -base64 32